version: '3'

services:
    elasticsearch:
      image: elasticsearch:5.6.4
      environment:
        ES_JAVA_OPTS: -Xms2g -Xmx2g
      command: -Enode.name=jaegerESNode
      restart: always
      volumes:
        - "esdata:/usr/share/elasticsearch/data"
      ports:
        - "9200:9200"
        - "9300:9300"
        
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      environment:
        SPAN_STORAGE_TYPE: elasticsearch
        ES_SERVER_URLS: http://elasticsearch:9200
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure
      links: ["elasticsearch:elasticsearch"]

    jaeger-query:
      image: jaegertracing/jaeger-query
      environment:
        SPAN_STORAGE_TYPE: elasticsearch
        ES_SERVER_URLS: http://elasticsearch:9200
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      links: ["elasticsearch:elasticsearch"]
    
    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--collector.host-port=jaeger-collector:14267"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/esdata"